package com.sblm.model3;

// Generated 05-ago-2013 16:25:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Asunto generated by hbm2java
 */
@Entity
@Table(name = "ASUNTO", schema = "dbo", catalog = "beneficenciadba")
public class Asunto implements java.io.Serializable {

	private int idasunto;
	private String codigoasunto;
	private String descripcionasunto;

	public Asunto() {
	}

	public Asunto(int idasunto) {
		this.idasunto = idasunto;
	}

	public Asunto(int idasunto, String codigoasunto, String descripcionasunto) {
		this.idasunto = idasunto;
		this.codigoasunto = codigoasunto;
		this.descripcionasunto = descripcionasunto;
	}

	@Id
	@Column(name = "IDASUNTO", unique = true, nullable = false)
	public int getIdasunto() {
		return this.idasunto;
	}

	public void setIdasunto(int idasunto) {
		this.idasunto = idasunto;
	}

	@Column(name = "CODIGOASUNTO", length = 4)
	public String getCodigoasunto() {
		return this.codigoasunto;
	}

	public void setCodigoasunto(String codigoasunto) {
		this.codigoasunto = codigoasunto;
	}

	@Column(name = "DESCRIPCIONASUNTO", length = 100)
	public String getDescripcionasunto() {
		return this.descripcionasunto;
	}

	public void setDescripcionasunto(String descripcionasunto) {
		this.descripcionasunto = descripcionasunto;
	}

}
