package com.sblm.model3;

// Generated 05-ago-2013 16:25:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Flujodocumento generated by hbm2java
 */
@Entity
@Table(name = "FLUJODOCUMENTO", schema = "dbo", catalog = "beneficenciadba")
public class Flujodocumento implements java.io.Serializable {

	private int idflujodocumento;
	private Perfilusuario perfilusuario;
	private Documento documento;
	private Area area;
	private Usuario usuario;
	private Integer numero;
	private Integer idusuarioremitente;
	private Date fechamodificacion;
	private Date fechaenvio;
	private Date fecharecepcion;
	private String respuesta;
	private String comentario;
	private Boolean estadoenvio;
	private Boolean estadorecepcion;
	private Boolean estado;

	public Flujodocumento() {
	}

	public Flujodocumento(int idflujodocumento) {
		this.idflujodocumento = idflujodocumento;
	}

	public Flujodocumento(int idflujodocumento, Perfilusuario perfilusuario,
			Documento documento, Area area, Usuario usuario, Integer numero,
			Integer idusuarioremitente, Date fechamodificacion,
			Date fechaenvio, Date fecharecepcion, String respuesta,
			String comentario, Boolean estadoenvio, Boolean estadorecepcion,
			Boolean estado) {
		this.idflujodocumento = idflujodocumento;
		this.perfilusuario = perfilusuario;
		this.documento = documento;
		this.area = area;
		this.usuario = usuario;
		this.numero = numero;
		this.idusuarioremitente = idusuarioremitente;
		this.fechamodificacion = fechamodificacion;
		this.fechaenvio = fechaenvio;
		this.fecharecepcion = fecharecepcion;
		this.respuesta = respuesta;
		this.comentario = comentario;
		this.estadoenvio = estadoenvio;
		this.estadorecepcion = estadorecepcion;
		this.estado = estado;
	}

	@Id
	@Column(name = "IDFLUJODOCUMENTO", unique = true, nullable = false)
	public int getIdflujodocumento() {
		return this.idflujodocumento;
	}

	public void setIdflujodocumento(int idflujodocumento) {
		this.idflujodocumento = idflujodocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPERFILUSUARIO")
	public Perfilusuario getPerfilusuario() {
		return this.perfilusuario;
	}

	public void setPerfilusuario(Perfilusuario perfilusuario) {
		this.perfilusuario = perfilusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDOCUMENTO")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDAREA")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIODESTINO")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "NUMERO")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "IDUSUARIOREMITENTE")
	public Integer getIdusuarioremitente() {
		return this.idusuarioremitente;
	}

	public void setIdusuarioremitente(Integer idusuarioremitente) {
		this.idusuarioremitente = idusuarioremitente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAMODIFICACION", length = 23)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAENVIO", length = 23)
	public Date getFechaenvio() {
		return this.fechaenvio;
	}

	public void setFechaenvio(Date fechaenvio) {
		this.fechaenvio = fechaenvio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHARECEPCION", length = 23)
	public Date getFecharecepcion() {
		return this.fecharecepcion;
	}

	public void setFecharecepcion(Date fecharecepcion) {
		this.fecharecepcion = fecharecepcion;
	}

	@Column(name = "RESPUESTA", length = 100)
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Column(name = "COMENTARIO", length = 500)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "ESTADOENVIO")
	public Boolean getEstadoenvio() {
		return this.estadoenvio;
	}

	public void setEstadoenvio(Boolean estadoenvio) {
		this.estadoenvio = estadoenvio;
	}

	@Column(name = "ESTADORECEPCION")
	public Boolean getEstadorecepcion() {
		return this.estadorecepcion;
	}

	public void setEstadorecepcion(Boolean estadorecepcion) {
		this.estadorecepcion = estadorecepcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
